services:

  mongo:
    image: mongo
    restart: always
    
    environment:
    
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: java_mongodb
      
    ports:
      - "27017:27017"
    
    volumes:
      - ./.db:/data/db